apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: "db-fun"
spec:
  organization: dev-venkata
  secretsMountPath: "/tmp/secrets"
  module:
    source: "GoogleCloudPlatform/sql-db/google//modules/postgresql"
    version: "8.0.0"
