apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: "db-fun-1"
spec:
  organization: dev-venkata
  secretsMountPath: "/tmp/secrets"
  module:
    source: "git::https://github.com/GlueOps/terraform-gcp-cloud-sql.git"
  outputs:
    - key: TOGGLED_SWITCH
      moduleOutputName: TOGGLED_SWITCH
  variables:
    - key: GOOGLE_CREDENTIALS
      sensitive: true
      environmentVariable: true
    - key: TOGGLE_TO_RETRY
      sensitive: false
      value: '"12"'
      environmentVariable: true

