apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: "db-fun"
spec:
  organization: dev-venkata
  secretsMountPath: "/tmp/secrets"
  module:
    source: "git::https://github.com/GlueOps/terraform-gcp-cloud-sql.git"
    
    
