apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: "db-fun"
spec:
  organization: dev-venkata
  secretsMountPath: "/tmp/secrets"
  module:
    source: "git::ssh://git@github.com:google-terraform-modules/terraform-google-cloudsql.git"
  outputs:
    - key: instance_sql_ipv4
      moduleOutputName: instance_sql_ipv4
    - key: instance_sql_ipv4_time_to_retire
      moduleOutputName: instance_sql_ipv4_time_to_retire
  variables:
    - key: general
      value: |
          {
              name       = "mydatabase"
              env        = "dev"
              region     = "us-central1"
              db_version = "POSTGRES_14"
            }
      hcl: true
      sensitive: false
      environmentVariable: false
    - key: instance
      value: |
       {
          zone = "b"
        }
      hcl: true
      sensitive: false
      environmentVariable: false
