---
apiVersion: app.terraform.io/v1alpha1
kind: Workspace
metadata:
  name: "random"
spec:
  organization: dev-venkata
  secretsMountPath: "/tmp/secrets"
  module:
    source: "github.com/koikonom/terraform-nullresource-example"
 variables:
   - key: CONFIRM_DESTROY
     value: "1"
     sensitive: false
     environmentVariable: true
 outputs:
   - key: pet
     moduleOutputName: rofl
      environmentVariable: true
